//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderTracking
    {
        public int Id { get; set; }
        public Nullable<int> adduser { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public string contents { get; set; }
        public string remarks { get; set; }
        public Nullable<int> status { get; set; }
    }
}
