//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderProlist
    {
        public int Id { get; set; }
        public Nullable<int> saleorderid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> amount { get; set; }
        public string remark { get; set; }
        public Nullable<int> status { get; set; }
    }
}
