//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public int Id { get; set; }
        public string orderno { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public Nullable<System.DateTime> uptimedate { get; set; }
        public Nullable<int> customid { get; set; }
        public Nullable<int> executionstatus { get; set; }
        public Nullable<int> auditstatus { get; set; }
        public Nullable<int> adduser { get; set; }
        public Nullable<int> saleuser { get; set; }
        public Nullable<int> audituser { get; set; }
        public Nullable<System.DateTime> auditdate { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> status { get; set; }
        public string evaluation { get; set; }
    }
}
