//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleProduct
    {
        public int Id { get; set; }
        public string no { get; set; }
        public string cnname { get; set; }
        public string enname { get; set; }
        public string casno { get; set; }
        public Nullable<double> invotory { get; set; }
        public Nullable<double> price { get; set; }
        public string stand { get; set; }
        public string purity { get; set; }
        public Nullable<int> cataId { get; set; }
        public Nullable<int> breadid { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public Nullable<System.DateTime> uptimedate { get; set; }
        public Nullable<int> adduserid { get; set; }
    }
}
