//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleWarning
    {
        public int Id { get; set; }
        public Nullable<int> adduser { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<System.DateTime> lastdatetime { get; set; }
        public Nullable<int> type { get; set; }
        public string title { get; set; }
        public string contens { get; set; }
        public Nullable<int> status { get; set; }
    }
}
