//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string account { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string portraitico { get; set; }
        public string sex { get; set; }
        public Nullable<int> age { get; set; }
        public string zhiwei { get; set; }
        public string address { get; set; }
        public Nullable<int> rolulevel { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public Nullable<System.DateTime> uptdate { get; set; }
        public Nullable<int> status { get; set; }
    }
}
